# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/SongAmbassador_API
    docker:
      - image: circleci/node:6
        environment:
          PGHOST: 127.0.0.1
          PGUSER: blah
          NODE_ENV: development
      - image: circleci/postgres:11.2
        environment:
          POSTGRES_USER: blah
          POSTGRES_PASSWORD: ""
          POSTGRES_DB: favorites

    steps:
      - checkout

      - run: npm install
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: install postgresql-client
          command: |
            sudo apt-get update
            sudo apt-get install postgresql-client
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: test
          command: |
            knex migrate:latest
            knex seed:run
            mocha --exit
      - run:
          name: Deploy Master to Heroku
          command:
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
